# Generated by Django 5.2 on 2026-04-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"ordering": ["-date_added"], "verbose_name_plural": "entries"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.CharField(blank=True, max_length=255, verbose_name="笔记标签"),
        ),
        migrations.AddField(
            model_name="entry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="topic",
            name="category_color",
            field=models.CharField(
                default="#3B82F6", max_length=7, verbose_name="分类颜色"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=models.CharField(blank=True, max_length=255, verbose_name="分类标签"),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.TextField(verbose_name="笔记内容"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="learning_logs.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="text",
            field=models.CharField(max_length=200, verbose_name="分类名称"),
        ),
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField(verbose_name="打卡日期")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="打卡备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="打卡时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checkin_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "checkin_date"),
                        name="unique_owner_daily_checkin",
                    )
                ],
            },
        ),
    ]
