# Generated by Django 5.2 on 2026-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_logs",
            "0004_alter_entry_options_alter_topic_options_entry_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-is_pinned", "-pinned_at", "-date_added"],
                "verbose_name_plural": "entries",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["sort_order", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="entry",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="entry",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AddField(
            model_name="entry",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
        migrations.AddField(
            model_name="entry",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置顶时间"),
        ),
        migrations.AddField(
            model_name="topic",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序值"),
        ),
    ]
