# Generated by Django 5.2 on 2026-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weekly_target",
            field=models.PositiveIntegerField(
                default=10, verbose_name="每周目标笔记数"
            ),
        ),
    ]
