# Generated by Django 5.2 on 2026-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_weekly_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.CharField(blank=True, max_length=56, verbose_name="个性签名"),
        ),
    ]
